name: Recommendation system models


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        java-version: [8]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip==23.0.1 setuptools wheel
          python3 -m pip install flake8
      - name: Lint with flake8, type check with mypy
        run: |
          flake8 ./feature_manager ./models
          mypy --show-traceback ./feature_manager ./models
